language: java
jdk:
  - oraclejdk8

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

git:
  depth: 3
env:
  matrix:
    - GRADLE_OPTS="-Xms1g -Xmx3g"
before_install:
  - chmod +x gradlew
install: true
script: "./gradlew build"

notifications:
  irc:
    channels: "irc.esper.net#nucleus"
    template:
      - "Travis: %{repository}/%{branch} (%{commit}) : '%{commit_message}' by %{author}"
      - "Result: %{result}. %{message}"
      - "Build details: %{build_url}"
